apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c46yuwt05-nodejs
  janus-idp.io/tekton: c46yuwt05-nodejs
  backstage.io/kubernetes-id: c46yuwt05-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c46yuwt05-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
